version: '3.4'

services:
  dnsy.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro