apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsy-api-storage-pvc
  namespace: dnsy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi